/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TodoIdEditImport } from './routes/todo.$id.edit'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TodoIdEditRoute = TodoIdEditImport.update({
  id: '/todo/$id/edit',
  path: '/todo/$id/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/todo/$id/edit': {
      id: '/todo/$id/edit'
      path: '/todo/$id/edit'
      fullPath: '/todo/$id/edit'
      preLoaderRoute: typeof TodoIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todo/$id/edit': typeof TodoIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todo/$id/edit': typeof TodoIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/todo/$id/edit': typeof TodoIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todo/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todo/$id/edit'
  id: '__root__' | '/' | '/todo/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodoIdEditRoute: typeof TodoIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodoIdEditRoute: TodoIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/todo/$id/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/todo/$id/edit": {
      "filePath": "todo.$id.edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
